name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    uses: ./.github/workflows/reusable_build.yml
  playaround:
      runs-on: ubuntu-latest
      steps:
        - name: test print
          run: echo "TEST!"
  